## Demonstation of the reshape function

You will often find the reshape function useful when working with data. It allows you to change the shape of an array without changing its data. For example, if you have a one-dimensional array with 12 elements, you can reshape it into a 3x4 array. The only requirement is that the size of the initial array must match the size of the reshaped array.

In [98]:
import numpy as np
import pandas as pd



In [123]:
# create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],[13,14,15]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [124]:
arr.shape

(5, 3)

In [125]:
arr.ndim

2

## Reshaping an array

In [139]:
arr=arr.reshape(-1,1)

In [127]:
arr.shape

(15, 1)

In [128]:
arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [129]:
arr.ndim

2

In [130]:
arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [131]:
arr=arr.reshape(-1)

In [132]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
arr.shape

(12,)

In [92]:
arr.ndim

1

In [134]:
arr=arr.reshape(15)

In [135]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
arr.shape

(12,)

In [97]:
arr.ndim

1

In [66]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

## Use the ravel function to 'flatte' any array

In [70]:
arr.ravel() # same as reshape(-1), it flattens the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Reshaping and flattening pandas dataframes

In [71]:
df = pd.DataFrame(arr, columns=('x1', 'x2', 'y'))
df

x1  x2   y
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [72]:
np.ravel(df)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
arr2 = np.array(df).reshape(6,2)
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [74]:
df2 = pd.DataFrame(arr2, columns=('x1', 'x2'))
df2

x1  x2
0   1   2
1   3   4
2   5   6
3   7   8
4   9  10
5  11  12